name: places
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
        - asset: res/fonts/Roboto/Roboto-Medium.ttf
          weight: 600
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
  assets:
    - res/images/
    - res/icons/
    - res/icons/bottom_nav/
  uses-material-design: true